 Concession_ConcessionAuthorityID_104_Table select ConcessionAuthorityID, count(*) from Concession group by ConcessionAuthorityID
  Concession_DepartmentID_1008_Table select DepartmentID, count(*) from Concession group by DepartmentID
  ConcessionSub_BRDeviation_CON_BR_DEVIATION_Table select BRDeviation, count(*) from ConcessionSub group by BRDeviation
  ConcessionSub_ConcessionType_CON_CONCESSION_T_Table select ConcessionType, count(*) from ConcessionSub group by ConcessionType
  ConcessionSub_CWEStatusID_CON_CWE_STATUS_Table select CWEStatusID, count(*) from ConcessionSub group by CWEStatusID
  ConcessionSub_DesignAuthorityDecision_CON_DA_DECISION_Table select DesignAuthorityDecision, count(*) from ConcessionSub group by DesignAuthorityDecision
  ConcessionSub_DARAction_CON_DAR_ACTION_Table select DARAction, count(*) from ConcessionSub group by DARAction
  ConcessionSub_DrawingDeviation_CON_DRAWING_DEVI_Table select DrawingDeviation, count(*) from ConcessionSub group by DrawingDeviation
  ConcessionSub_FirstLevelAffected_CON_FIRST_LEVEL__Table select FirstLevelAffected, count(*) from ConcessionSub group by FirstLevelAffected
  ConcessionSub_FunctioningAffected_CON_FUNCTION_AFF_Table select FunctioningAffected, count(*) from ConcessionSub group by FunctioningAffected
  ConcessionSub_HandbookDeviation_CON_HANDBOOK_DEV_Table select HandbookDeviation, count(*) from ConcessionSub group by HandbookDeviation
  ConcessionSub_LayoutDeviation_CON_LAYOUT_DEVIA_Table select LayoutDeviation, count(*) from ConcessionSub group by LayoutDeviation
  ConcessionSub_ImpactAnalysisGroup_CON_IMPACT_ANALY_Table select ImpactAnalysisGroup, count(*) from ConcessionSub group by ImpactAnalysisGroup
  ConcessionSub_InterchangeabilityAffected_CON_INTERCHANGE__Table select InterchangeabilityAffected, count(*) from ConcessionSub group by InterchangeabilityAffected
  ConcessionSub_LifeOfItemAffected_CON_ITEM_LIFE_AF_Table select LifeOfItemAffected, count(*) from ConcessionSub group by LifeOfItemAffected
  ConcessionSub_MaintenanceAffected_CON_MAINTENANCE__Table select MaintenanceAffected, count(*) from ConcessionSub group by MaintenanceAffected
  ConcessionSub_NuclearImplication_CON_NUCLEAR_IMPL_Table select NuclearImplication, count(*) from ConcessionSub group by NuclearImplication
  ConcessionSub_NuclearSafetyAffected_CON_NUCLEAR_SAFE_Table select NuclearSafetyAffected, count(*) from ConcessionSub group by NuclearSafetyAffected
  ConcessionSub_PersonnelSafetyAffected_CON_PERSONNEL_SA_Table select PersonnelSafetyAffected, count(*) from ConcessionSub group by PersonnelSafetyAffected
  ConcessionSub_PositionDeviation_CON_POSITION_DEV_Table select PositionDeviation, count(*) from ConcessionSub group by PositionDeviation
  ConcessionSub_RaisedByID_CON_RAISED_BY_Table select RaisedByID, count(*) from ConcessionSub group by RaisedByID
  ConcessionSub_RevalidationAffected_CON_REVALIDATION_Table select RevalidationAffected, count(*) from ConcessionSub group by RevalidationAffected
  ConcessionSub_SpecificationDeviation_CON_SPEC_DEVIATI_Table select SpecificationDeviation, count(*) from ConcessionSub group by SpecificationDeviation
  ConcessionSub_StatusID_CON_STATUS_Table select StatusID, count(*) from ConcessionSub group by StatusID
  ConcessionSub_StrengthAffected_CON_STRENGTH_AFF_Table select StrengthAffected, count(*) from ConcessionSub group by StrengthAffected
  ConcessionSub_SubmarineSafetyAffected_CON_SUBMARINE_SA_Table select SubmarineSafetyAffected, count(*) from ConcessionSub group by SubmarineSafetyAffected
  ConcessionSub_TargetEventType_CON_TARGET_EVENT?_Table select TargetEventType, count(*) from ConcessionSub group by TargetEventType
  ConcessionSub_UseMaterials_CON_USE_MATERIAL_Table select UseMaterials, count(*) from ConcessionSub group by UseMaterials
  ConcessionSub_UseSpareGear_CON_USE_SPARE_GEC_Table select UseSpareGear, count(*) from ConcessionSub group by UseSpareGear
  ConcessionSub_UseStores_CON_USE_STORES_Table select UseStores, count(*) from ConcessionSub group by UseStores
  ConcessionSub_VitalSystemsAffected_CON_VITAL_SYSTEM_Table select VitalSystemsAffected, count(*) from ConcessionSub group by VitalSystemsAffected
  ConcessionSub_DepartmentID_1008_Table select DepartmentID, count(*) from ConcessionSub group by DepartmentID
  ConcessionSub_ENVIRONMENT_AFFECTED_CON_ENVIRONMENT__Table select ENVIRONMENT_AFFECTED, count(*) from ConcessionSub group by ENVIRONMENT_AFFECTED
  ConcessionSub_LOGISTICS_AFFECTED_CON_LOGISTICS_AF_Table select LOGISTICS_AFFECTED, count(*) from ConcessionSub group by LOGISTICS_AFFECTED
  ConcessionSub_NRP_CATEGORY_CON_NRP_CATEGORY_Table select NRP_CATEGORY, count(*) from ConcessionSub group by NRP_CATEGORY
  ConcessionSub_NRP_IMPACT_CON_NRP_IMPACT_Table select NRP_IMPACT, count(*) from ConcessionSub group by NRP_IMPACT
  Defect_HowFoundID_HOWFOUND_Table select HowFoundID, count(*) from Defect group by HowFoundID
  Defect_NONRCMFMLookUpID_NONRCMFAILCAUSE_Table select NONRCMFMLookUpID, count(*) from Defect group by NONRCMFMLookUpID
  Defect_PriorityID_NEW_DEFECT_PTY_Table select PriorityID, count(*) from Defect group by PriorityID
  Defect_RepairableAtSea_DEF_REPAIRED_AT__Table select RepairableAtSea, count(*) from Defect group by RepairableAtSea
  Defect_EquipEffectID_EQUIPEFFECT_Table select EquipEffectID, count(*) from Defect group by EquipEffectID
  Defect_SystemEffectID_EQUIPEFFECT_Table select SystemEffectID, count(*) from Defect group by SystemEffectID
  Defect_SoftwareFault_DEF_SOFTWARE_FAU_Table select SoftwareFault, count(*) from Defect group by SoftwareFault
  Defect_BITEDetected_DEF_BITE_DEFECTE_Table select BITEDetected, count(*) from Defect group by BITEDetected
  Defect_FirstLevel_DEF_FIRST_LEVEL_Table select FirstLevel, count(*) from Defect group by FirstLevel
  Defect_DiscoveredAtSea_DEF_DISCOVERED_A_Table select DiscoveredAtSea, count(*) from Defect group by DiscoveredAtSea
  Defect_ImmediateShutdown_DEF_IMMEDIATE_SH_Table select ImmediateShutdown, count(*) from Defect group by ImmediateShutdown
  Defect_RepairedAtSea_DEF_REPAIRED_AT__Table select RepairedAtSea, count(*) from Defect group by RepairedAtSea
  Defect_OperableUntilRepair_DEF_OPERABLE_UNT_Table select OperableUntilRepair, count(*) from Defect group by OperableUntilRepair
  Defect_ShutDownForRepair_DEF_SHUTDOWN_FOR_Table select ShutDownForRepair, count(*) from Defect group by ShutDownForRepair
  Defect_DepartmentID_DEPARTMENT_Table select DepartmentID, count(*) from Defect group by DepartmentID
  Defect_NONRCMFELookUpID_DEF_FAILURE_EFFE_Table select NONRCMFELookUpID, count(*) from Defect group by NONRCMFELookUpID
  Defect_WorkDoneByShipStaff_DEF_WORK_DONE_BY_Table select WorkDoneByShipStaff, count(*) from Defect group by WorkDoneByShipStaff
  Defect_Original_DepartmentID_DEPARTMENT_Table select Original_DepartmentID, count(*) from Defect group by Original_DepartmentID
  Defect_Original_PriorityID_NEW_DEFECT_PTY_Table select Original_PriorityID, count(*) from Defect group by Original_PriorityID
  Job_JobStatusID_5_Table select JobStatusID, count(*) from Job group by JobStatusID
  Job_DepartmentID__Table select DepartmentID, count(*) from Job group by DepartmentID
  JobPart_QuantityID_DofQ_Table select QuantityID, count(*) from JobPart group by QuantityID
  Ripout_StatusID_82_Table select StatusID, count(*) from Ripout group by StatusID
  RipOutHistory_RipoutStatus_82_Table select RipoutStatus, count(*) from RipOutHistory group by RipoutStatus
  S2022_DefectReplyStatus_DEF_STATUS_Table select DefectReplyStatus, count(*) from S2022 group by DefectReplyStatus
  S2022_OPDEF1_OPDEFTYPE_Table select OPDEF1, count(*) from S2022 group by OPDEF1
  S2022_ReportCategory_63_Table select ReportCategory, count(*) from S2022 group by ReportCategory
  S2022_RiskCategory_65_Table select RiskCategory, count(*) from S2022 group by RiskCategory
  S2022_RiskFrequency_61_Table select RiskFrequency, count(*) from S2022 group by RiskFrequency
  S2022_RiskSeverity_62_Table select RiskSeverity, count(*) from S2022 group by RiskSeverity
  S2022_S2022Priority_DEF_PRIORITY_Table select S2022Priority, count(*) from S2022 group by S2022Priority
  S2022_S2022StatusID_60_Table select S2022StatusID, count(*) from S2022 group by S2022StatusID
  S2022_SafetyImplication_1022_Table select SafetyImplication, count(*) from S2022 group by SafetyImplication
  Task_SFMTradeID_SFMTRADE_Table select SFMTradeID, count(*) from Task group by SFMTradeID
  Task_TaskCatID_TaskCategory_Table select TaskCatID, count(*) from Task group by TaskCatID
  Task_TaskStatusID_500_Table select TaskStatusID, count(*) from Task group by TaskStatusID
  Task_SecurityText_124_Table select SecurityText, count(*) from Task group by SecurityText
  TaskPart_QuantityID_DofQ_Table select QuantityID, count(*) from TaskPart group by QuantityID
 