Concession_ConcessionAuthorityID_104_Table select ConcessionAuthorityID, count(*) from Concession where ConcessionAuthorityID is not null group by ConcessionAuthorityID order by ConcessionAuthorityID
Concession_DepartmentID_1008_Table select DepartmentID, count(*) from Concession where DepartmentID is not null group by DepartmentID order by DepartmentID
ConcessionSub_BRDeviation_CON_BR_DEVIATION_Table select BRDeviation, count(*) from ConcessionSub where BRDeviation is not null group by BRDeviation order by BRDeviation
ConcessionSub_ConcessionType_CON_CONCESSION_T_Table select ConcessionType, count(*) from ConcessionSub where ConcessionType is not null group by ConcessionType order by ConcessionType
ConcessionSub_CWEStatusID_CON_CWE_STATUS_Table select CWEStatusID, count(*) from ConcessionSub where CWEStatusID is not null group by CWEStatusID order by CWEStatusID
ConcessionSub_DesignAuthorityDecision_CON_DA_DECISION_Table select DesignAuthorityDecision, count(*) from ConcessionSub where DesignAuthorityDecision is not null group by DesignAuthorityDecision order by DesignAuthorityDecision
ConcessionSub_DARAction_CON_DAR_ACTION_Table select DARAction, count(*) from ConcessionSub where DARAction is not null group by DARAction order by DARAction
ConcessionSub_DrawingDeviation_CON_DRAWING_DEVI_Table select DrawingDeviation, count(*) from ConcessionSub where DrawingDeviation is not null group by DrawingDeviation order by DrawingDeviation
ConcessionSub_FirstLevelAffected_CON_FIRST_LEVEL__Table select FirstLevelAffected, count(*) from ConcessionSub where FirstLevelAffected is not null group by FirstLevelAffected order by FirstLevelAffected
ConcessionSub_FunctioningAffected_CON_FUNCTION_AFF_Table select FunctioningAffected, count(*) from ConcessionSub where FunctioningAffected is not null group by FunctioningAffected order by FunctioningAffected
ConcessionSub_HandbookDeviation_CON_HANDBOOK_DEV_Table select HandbookDeviation, count(*) from ConcessionSub where HandbookDeviation is not null group by HandbookDeviation order by HandbookDeviation
ConcessionSub_LayoutDeviation_CON_LAYOUT_DEVIA_Table select LayoutDeviation, count(*) from ConcessionSub where LayoutDeviation is not null group by LayoutDeviation order by LayoutDeviation
ConcessionSub_ImpactAnalysisGroup_CON_IMPACT_ANALY_Table select ImpactAnalysisGroup, count(*) from ConcessionSub where ImpactAnalysisGroup is not null group by ImpactAnalysisGroup order by ImpactAnalysisGroup
ConcessionSub_InterchangeabilityAffected_CON_INTERCHANGE__Table select InterchangeabilityAffected, count(*) from ConcessionSub where InterchangeabilityAffected is not null group by InterchangeabilityAffected order by InterchangeabilityAffected
ConcessionSub_LifeOfItemAffected_CON_ITEM_LIFE_AF_Table select LifeOfItemAffected, count(*) from ConcessionSub where LifeOfItemAffected is not null group by LifeOfItemAffected order by LifeOfItemAffected
ConcessionSub_MaintenanceAffected_CON_MAINTENANCE__Table select MaintenanceAffected, count(*) from ConcessionSub where MaintenanceAffected is not null group by MaintenanceAffected order by MaintenanceAffected
ConcessionSub_NuclearImplication_CON_NUCLEAR_IMPL_Table select NuclearImplication, count(*) from ConcessionSub where NuclearImplication is not null group by NuclearImplication order by NuclearImplication
ConcessionSub_NuclearSafetyAffected_CON_NUCLEAR_SAFE_Table select NuclearSafetyAffected, count(*) from ConcessionSub where NuclearSafetyAffected is not null group by NuclearSafetyAffected order by NuclearSafetyAffected
ConcessionSub_PersonnelSafetyAffected_CON_PERSONNEL_SA_Table select PersonnelSafetyAffected, count(*) from ConcessionSub where PersonnelSafetyAffected is not null group by PersonnelSafetyAffected order by PersonnelSafetyAffected
ConcessionSub_PositionDeviation_CON_POSITION_DEV_Table select PositionDeviation, count(*) from ConcessionSub where PositionDeviation is not null group by PositionDeviation order by PositionDeviation
ConcessionSub_RaisedByID_CON_RAISED_BY_Table select RaisedByID, count(*) from ConcessionSub where RaisedByID is not null group by RaisedByID order by RaisedByID
ConcessionSub_RevalidationAffected_CON_REVALIDATION_Table select RevalidationAffected, count(*) from ConcessionSub where RevalidationAffected is not null group by RevalidationAffected order by RevalidationAffected
ConcessionSub_SpecificationDeviation_CON_SPEC_DEVIATI_Table select SpecificationDeviation, count(*) from ConcessionSub where SpecificationDeviation is not null group by SpecificationDeviation order by SpecificationDeviation
ConcessionSub_StatusID_CON_STATUS_Table select StatusID, count(*) from ConcessionSub where StatusID is not null group by StatusID order by StatusID
ConcessionSub_StrengthAffected_CON_STRENGTH_AFF_Table select StrengthAffected, count(*) from ConcessionSub where StrengthAffected is not null group by StrengthAffected order by StrengthAffected
ConcessionSub_SubmarineSafetyAffected_CON_SUBMARINE_SA_Table select SubmarineSafetyAffected, count(*) from ConcessionSub where SubmarineSafetyAffected is not null group by SubmarineSafetyAffected order by SubmarineSafetyAffected
ConcessionSub_TargetEventType_CON_TARGET_EVENT?_Table select TargetEventType, count(*) from ConcessionSub where TargetEventType is not null group by TargetEventType order by TargetEventType
ConcessionSub_UseMaterials_CON_USE_MATERIAL_Table select UseMaterials, count(*) from ConcessionSub where UseMaterials is not null group by UseMaterials order by UseMaterials
ConcessionSub_UseSpareGear_CON_USE_SPARE_GEC_Table select UseSpareGear, count(*) from ConcessionSub where UseSpareGear is not null group by UseSpareGear order by UseSpareGear
ConcessionSub_UseStores_CON_USE_STORES_Table select UseStores, count(*) from ConcessionSub where UseStores is not null group by UseStores order by UseStores
ConcessionSub_VitalSystemsAffected_CON_VITAL_SYSTEM_Table select VitalSystemsAffected, count(*) from ConcessionSub where VitalSystemsAffected is not null group by VitalSystemsAffected order by VitalSystemsAffected
ConcessionSub_DepartmentID_1008_Table select DepartmentID, count(*) from ConcessionSub where DepartmentID is not null group by DepartmentID order by DepartmentID
ConcessionSub_ENVIRONMENT_AFFECTED_CON_ENVIRONMENT__Table select ENVIRONMENT_AFFECTED, count(*) from ConcessionSub where ENVIRONMENT_AFFECTED is not null group by ENVIRONMENT_AFFECTED order by ENVIRONMENT_AFFECTED
ConcessionSub_LOGISTICS_AFFECTED_CON_LOGISTICS_AF_Table select LOGISTICS_AFFECTED, count(*) from ConcessionSub where LOGISTICS_AFFECTED is not null group by LOGISTICS_AFFECTED order by LOGISTICS_AFFECTED
ConcessionSub_NRP_CATEGORY_CON_NRP_CATEGORY_Table select NRP_CATEGORY, count(*) from ConcessionSub where NRP_CATEGORY is not null group by NRP_CATEGORY order by NRP_CATEGORY
ConcessionSub_NRP_IMPACT_CON_NRP_IMPACT_Table select NRP_IMPACT, count(*) from ConcessionSub where NRP_IMPACT is not null group by NRP_IMPACT order by NRP_IMPACT
Defect_HowFoundID_HOWFOUND_Table select HowFoundID, count(*) from Defect where HowFoundID is not null group by HowFoundID order by HowFoundID
Defect_NONRCMFMLookUpID_NONRCMFAILCAUSE_Table select NONRCMFMLookUpID, count(*) from Defect where NONRCMFMLookUpID is not null group by NONRCMFMLookUpID order by NONRCMFMLookUpID
Defect_PriorityID_NEW_DEFECT_PTY_Table select PriorityID, count(*) from Defect where PriorityID is not null group by PriorityID order by PriorityID
Defect_RepairableAtSea_DEF_REPAIRED_AT__Table select RepairableAtSea, count(*) from Defect where RepairableAtSea is not null group by RepairableAtSea order by RepairableAtSea
Defect_EquipEffectID_EQUIPEFFECT_Table select EquipEffectID, count(*) from Defect where EquipEffectID is not null group by EquipEffectID order by EquipEffectID
Defect_SystemEffectID_EQUIPEFFECT_Table select SystemEffectID, count(*) from Defect where SystemEffectID is not null group by SystemEffectID order by SystemEffectID
Defect_SoftwareFault_DEF_SOFTWARE_FAU_Table select SoftwareFault, count(*) from Defect where SoftwareFault is not null group by SoftwareFault order by SoftwareFault
Defect_BITEDetected_DEF_BITE_DEFECTE_Table select BITEDetected, count(*) from Defect where BITEDetected is not null group by BITEDetected order by BITEDetected
Defect_FirstLevel_DEF_FIRST_LEVEL_Table select FirstLevel, count(*) from Defect where FirstLevel is not null group by FirstLevel order by FirstLevel
Defect_DiscoveredAtSea_DEF_DISCOVERED_A_Table select DiscoveredAtSea, count(*) from Defect where DiscoveredAtSea is not null group by DiscoveredAtSea order by DiscoveredAtSea
Defect_ImmediateShutdown_DEF_IMMEDIATE_SH_Table select ImmediateShutdown, count(*) from Defect where ImmediateShutdown is not null group by ImmediateShutdown order by ImmediateShutdown
Defect_RepairedAtSea_DEF_REPAIRED_AT__Table select RepairedAtSea, count(*) from Defect where RepairedAtSea is not null group by RepairedAtSea order by RepairedAtSea
Defect_OperableUntilRepair_DEF_OPERABLE_UNT_Table select OperableUntilRepair, count(*) from Defect where OperableUntilRepair is not null group by OperableUntilRepair order by OperableUntilRepair
Defect_ShutDownForRepair_DEF_SHUTDOWN_FOR_Table select ShutDownForRepair, count(*) from Defect where ShutDownForRepair is not null group by ShutDownForRepair order by ShutDownForRepair
Defect_DepartmentID_DEPARTMENT_Table select DepartmentID, count(*) from Defect where DepartmentID is not null group by DepartmentID order by DepartmentID
Defect_NONRCMFELookUpID_DEF_FAILURE_EFFE_Table select NONRCMFELookUpID, count(*) from Defect where NONRCMFELookUpID is not null group by NONRCMFELookUpID order by NONRCMFELookUpID
Defect_WorkDoneByShipStaff_DEF_WORK_DONE_BY_Table select WorkDoneByShipStaff, count(*) from Defect where WorkDoneByShipStaff is not null group by WorkDoneByShipStaff order by WorkDoneByShipStaff
Defect_Original_DepartmentID_DEPARTMENT_Table select Original_DepartmentID, count(*) from Defect where Original_DepartmentID is not null group by Original_DepartmentID order by Original_DepartmentID
Defect_Original_PriorityID_NEW_DEFECT_PTY_Table select Original_PriorityID, count(*) from Defect where Original_PriorityID is not null group by Original_PriorityID order by Original_PriorityID
Job_JobStatusID_5_Table select JobStatusID, count(*) from Job where JobStatusID is not null group by JobStatusID order by JobStatusID
Job_DepartmentID__Table select DepartmentID, count(*) from Job where DepartmentID is not null group by DepartmentID order by DepartmentID
JobPart_QuantityID_DofQ_Table select QuantityID, count(*) from JobPart where QuantityID is not null group by QuantityID order by QuantityID
Ripout_StatusID_82_Table select StatusID, count(*) from Ripout where StatusID is not null group by StatusID order by StatusID
RipOutHistory_RipoutStatus_82_Table select RipoutStatus, count(*) from RipOutHistory where RipoutStatus is not null group by RipoutStatus order by RipoutStatus
S2022_DefectReplyStatus_DEF_STATUS_Table select DefectReplyStatus, count(*) from S2022 where DefectReplyStatus is not null group by DefectReplyStatus order by DefectReplyStatus
S2022_OPDEF1_OPDEFTYPE_Table select OPDEF1, count(*) from S2022 where OPDEF1 is not null group by OPDEF1 order by OPDEF1
S2022_ReportCategory_63_Table select ReportCategory, count(*) from S2022 where ReportCategory is not null group by ReportCategory order by ReportCategory
S2022_RiskCategory_65_Table select RiskCategory, count(*) from S2022 where RiskCategory is not null group by RiskCategory order by RiskCategory
S2022_RiskFrequency_61_Table select RiskFrequency, count(*) from S2022 where RiskFrequency is not null group by RiskFrequency order by RiskFrequency
S2022_RiskSeverity_62_Table select RiskSeverity, count(*) from S2022 where RiskSeverity is not null group by RiskSeverity order by RiskSeverity
S2022_S2022Priority_DEF_PRIORITY_Table select S2022Priority, count(*) from S2022 where S2022Priority is not null group by S2022Priority order by S2022Priority
S2022_S2022StatusID_60_Table select S2022StatusID, count(*) from S2022 where S2022StatusID is not null group by S2022StatusID order by S2022StatusID
S2022_SafetyImplication_1022_Table select SafetyImplication, count(*) from S2022 where SafetyImplication is not null group by SafetyImplication order by SafetyImplication
Task_SFMTradeID_SFMTRADE_Table select SFMTradeID, count(*) from Task where SFMTradeID is not null group by SFMTradeID order by SFMTradeID
Task_TaskCatID_TaskCategory_Table select TaskCatID, count(*) from Task where TaskCatID is not null group by TaskCatID order by TaskCatID
Task_TaskStatusID_500_Table select TaskStatusID, count(*) from Task where TaskStatusID is not null group by TaskStatusID order by TaskStatusID
Task_SecurityText_124_Table select SecurityText, count(*) from Task where SecurityText is not null group by SecurityText order by SecurityText
TaskPart_QuantityID_DofQ_Table select QuantityID, count(*) from TaskPart where QuantityID is not null group by QuantityID order by QuantityID